#!/usr/bin/env bash
set -euo pipefail

# macOS fallback for Bash 3.2
if ((BASH_VERSINFO[0] < 4 || (BASH_VERSINFO[0] == 4 && BASH_VERSINFO[1] < 4))); then
    for b in /opt/homebrew/bin/bash /usr/local/bin/bash; do
        [[ -x "$b" ]] && exec "$b" "$0" "$@"
    done
    echo "ERROR: sync-docs.sh requires Bash 4.4+ (Git Bash / brew bash / Linux)." >&2
    exit 1
fi

if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    echo "ERROR: sync-docs.sh must be run inside a Git repository." >&2
    exit 1
fi

export LC_ALL=C
REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "$REPO_ROOT"

MAP_FILE="scripts/file-descriptions.txt"
OUT_FILE="docs/file-index.md"
CHECK_MODE=0
INDEX_MODE="${INDEX_MODE:-compact}"
MAX_INVENTORY_ROWS="${MAX_INVENTORY_ROWS:-40}"
MAX_INDEX_BYTES="${MAX_INDEX_BYTES:-20480}"

for arg in "$@"; do
    case "$arg" in
        --check) CHECK_MODE=1 ;;
        --full) INDEX_MODE="full" ;;
        --compact) INDEX_MODE="compact" ;;
        *) echo "ERROR: unknown arg: $arg" >&2; exit 2 ;;
    esac
done

EXCLUDE_RE='^(\.git/|docs/file-index\.md|docs/agent/HANDOVER\.md|\.kilo/cache/|\.kilo/tmp/)'

TMP_DIR="$(git rev-parse --git-path kilo-tmp)"
mkdir -p "$TMP_DIR"
RUN_TMP="$(mktemp -d "$TMP_DIR/sync-docs.XXXXXX")"
trap 'rm -rf -- "$RUN_TMP"' EXIT

make_tmp_file() { mktemp "$RUN_TMP/f.XXXXXX"; }

trim() {
    local s="$1"
    s="${s#"${s%%[![:space:]]*}"}"
    s="${s%"${s##*[![:space:]]}"}"
    printf '%s' "$s"
}

declare -A DESC_MAP=()
declare -A TRACKED=()

load_descriptions() {
    [[ -f "$MAP_FILE" ]] || return 0
    local line key val
    while IFS= read -r line || [[ -n "$line" ]]; do
        [[ "$line" =~ ^[[:space:]]*# ]] && continue
        [[ -z "${line//[[:space:]]/}" ]] && continue
        key="$(trim "${line%%:*}")"
        val="$(trim "${line#*:}")"
        [[ -n "$key" ]] && DESC_MAP["$key"]="$val"
    done < "$MAP_FILE"
}

md_cell() {
    local s="$1"
    s="${s//|/\\|}"
    s="${s//$'\n'/ }"
    printf '%s' "$s"
}

rollup_dir() {
    local file="$1"
    [[ "$file" == */* ]] || { printf '%s' "."; return 0; }
    local first="${file%%/*}" rest="${file#*/}"
    if [[ "$rest" == */* ]]; then
        printf '%s' "$first/${rest%%/*}"
    else
        printf '%s' "$first"
    fi
}

list_tracked() {
    local out="$1"
    : > "$out"
    local list file
    list="$(make_tmp_file)"
    git ls-files --cached -z > "$list"
    while IFS= read -r -d '' file; do
        [[ -n "$file" ]] || continue
        [[ "$file" =~ $EXCLUDE_RE ]] && continue
        TRACKED["$file"]=1
        printf '%s\0' "$file" >> "$out"
    done < "$list"
}

generate_doc() {
    local files="$1"
    echo "# File Index"
    echo ""
    echo "Generated by scripts/sync-docs.sh — do not edit manually."
    echo "Mode: $INDEX_MODE"
    echo ""

    echo "## Documented paths"
    echo ""
    echo "| Path | Purpose |"
    echo "|------|---------|"

    declare -A printed=()
    local file desc

    if [[ -f "$MAP_FILE" ]]; then
        local line key
        while IFS= read -r line || [[ -n "$line" ]]; do
            [[ "$line" =~ ^[[:space:]]*# ]] && continue
            [[ -z "${line//[[:space:]]/}" ]] && continue
            key="$(trim "${line%%:*}")"
            [[ -z "$key" ]] && continue
            [[ "$key" =~ $EXCLUDE_RE ]] && continue
            if [[ -n "${TRACKED[$key]+x}" ]]; then
                desc="${DESC_MAP[$key]:-}"
                if [[ -z "$desc" ]]; then
                    case "$key" in
                        *.py) desc="Python source" ;;
                        *.tf|*.tf.json) desc="Terraform" ;;
                        *.sh) desc="Shell script" ;;
                        *.md) desc="Documentation" ;;
                        *.json|*.jsonc) desc="JSON config" ;;
                        *.yml|*.yaml) desc="YAML config" ;;
                        *.toml) desc="TOML config" ;;
                        *.lock|*.lock.hcl) desc="Lockfile" ;;
                        *) desc="Project file" ;;
                    esac
                fi
                printf '| %s | %s |\n' "$(md_cell "$key")" "$(md_cell "$desc")"
                printed["$key"]=1
            fi
        done < "$MAP_FILE"
    fi

    while IFS= read -r -d '' file; do
        [[ "$file" == */* ]] && continue
        [[ -n "${printed[$file]+x}" ]] && continue
        desc="${DESC_MAP[$file]:-Project file}"
        printf '| %s | %s |\n' "$(md_cell "$file")" "$(md_cell "$desc")"
        printed["$file"]=1
    done < "$files"

    if [[ "$INDEX_MODE" == "full" ]]; then
        echo ""
        echo "## All tracked files"
        echo ""
        echo "| Path | Purpose |"
        echo "|------|---------|"
        while IFS= read -r -d '' file; do
            [[ -n "${printed[$file]+x}" ]] && continue
            desc="${DESC_MAP[$file]:-Project file}"
            printf '| %s | %s |\n' "$(md_cell "$file")" "$(md_cell "$desc")"
        done < "$files"
        return 0
    fi

    echo ""
    echo "## Directory inventory (depth ≤ 2, cap ${MAX_INVENTORY_ROWS})"
    echo ""
    echo "| Directory | Tracked files |"
    echo "|-----------|---------------|"

    declare -A counts=()
    local dir
    while IFS= read -r -d '' file; do
        dir="$(rollup_dir "$file")"
        counts["$dir"]=$(( ${counts[$dir]:-0} + 1 ))
    done < "$files"

    local keys
    keys="$(make_tmp_file)"
    for dir in "${!counts[@]}"; do
        printf '%s\n' "$dir"
    done | LC_ALL=C sort > "$keys"

    local shown=0 total_dirs=0 rest_files=0
    while IFS= read -r dir; do
        [[ -n "$dir" ]] || continue
        total_dirs=$((total_dirs + 1))
        if (( shown < MAX_INVENTORY_ROWS )); then
            printf '| %s | %s |\n' "$(md_cell "$dir")" "${counts[$dir]}"
            shown=$((shown + 1))
        else
            rest_files=$((rest_files + counts[$dir]))
        fi
    done < "$keys"

    if (( total_dirs > MAX_INVENTORY_ROWS )); then
        printf '| (%s more directories) | %s |\n' "$((total_dirs - MAX_INVENTORY_ROWS))" "$rest_files"
    fi
}

# Refuse to read through a symlinked descriptions file (could leak secrets).
if [[ -L "$MAP_FILE" ]]; then
    echo "ERROR: $MAP_FILE is a symlink; refusing to read through it." >&2
    exit 1
fi

load_descriptions
mkdir -p "$(dirname "$OUT_FILE")"

tracked="$(make_tmp_file)"
list_tracked "$tracked"

tmp_out="$(make_tmp_file)"
generate_doc "$tracked" > "$tmp_out"

# Index size limit check
sz=$(wc -c < "$tmp_out" | tr -d ' ')
if (( sz > MAX_INDEX_BYTES )); then
    echo "ERROR: $OUT_FILE index is ${sz} bytes (max ${MAX_INDEX_BYTES})." >&2
    exit 1
fi

# Refuse to write/check through a symlink (cp would follow it to the target).
if [[ -L "$OUT_FILE" ]]; then
    echo "ERROR: $OUT_FILE is a symlink; refusing to write or check through it." >&2
    exit 1
fi

if (( CHECK_MODE == 1 )); then
    # The generated index reflects the staged tracked set; verify against what
    # will actually be committed (staged blob), falling back to WT if unstaged.
    if git rev-parse --verify --quiet ":${OUT_FILE}" >/dev/null 2>&1; then
        cmp_target="$(make_tmp_file)"
        git show ":${OUT_FILE}" > "$cmp_target"
        cmp_label="staged"
    elif [[ -f "$OUT_FILE" ]]; then
        cmp_target="$OUT_FILE"
        cmp_label="working tree"
    else
        echo "ERROR: $OUT_FILE does not exist. Run 'bash scripts/sync-docs.sh' first." >&2
        exit 1
    fi
    if ! cmp -s "$cmp_target" "$tmp_out"; then
        echo "ERROR: $OUT_FILE ($cmp_label) is out of sync." >&2
        [[ "$cmp_label" == "staged" ]] && echo "  Regenerate and stage: bash scripts/sync-docs.sh && git add $OUT_FILE" >&2
        exit 1
    fi
    echo "[Docs] $OUT_FILE ($cmp_label) is in sync ($INDEX_MODE)"
else
    if [[ ! -f "$OUT_FILE" ]] || ! cmp -s "$OUT_FILE" "$tmp_out"; then
        cp -f "$tmp_out" "$OUT_FILE"
        echo "[Docs] Updated $OUT_FILE ($INDEX_MODE)"
    else
        echo "[Docs] $OUT_FILE is already up to date ($INDEX_MODE)"
    fi
fi
